#!/bin/sh
# PROVIDE: accmd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="accmd"
rcvar=`set_rcvar`
command="/begun/bin/accmd.pl"
command_args="-d -v"
pidfile="/var/run/${name}.pid"

load_rc_config $name

stop_cmd="echo \"Stopping ${name}.\"; kill `cat /var/run/accmd.pid`"

run_rc_command "$1"

